#pragma config(Motor,  port4,           RightBottomFly, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightTopFly,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftTopFly,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LeftBottomFly, tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int flySpeed;		//Flywheel speed variable

//|--- Stop the Flywheel ---|
task stopFlywheel()
{
	if (flySpeed > 64)
	{
		flySpeed = (flyspeed / 2);
		motor[LeftTopFly] = flySpeed;
		motor[RightBottomFly] = flySpeed;
		motor[LeftBottomFly] = flySpeed;
		motor[RightTopFly] = flySpeed;
	}
	else
	{
		motor[LeftTopFly] = 0;
		motor[RightBottomFly] = 0;
		motor[LeftBottomFly] = 0;
		motor[RightTopFly] = 0;
	}
}

//|--- Autonomous Flywheel ---|
void runFlywheel(int fSpeed)
{
	motor[RightTopFly] = fSpeed;
	motor[LeftBottomFly] = fSpeed;
}

//|--- Flyhweel Control ---|
void flyControl()
{
	int flySpeed;
	int flySetting = 5; 	//Flysetting defaults to mode 5 (127 power)

	//Switch flySetting
	if (vexRT[Btn8D] == 1)
	{
		if (flySetting > 0)
		{
			flySetting = flySetting - 1; 	//8D decreases power
		}
		else
		{
		}
	}

	else if (vexRT[Btn8R] == 1)
	{
		if (flySetting < 5)
		{
			flySetting = flySetting + 1; 		//8R increases power
		}
		else
		{
		}
	}

	else
	{
		flySetting = flySetting;		//If nothing is pressed, flywheel power stays the same
	}

	//Fire Flywheels
	if (vexRT[Btn5D] == 1)
	{

		stopTask(stopFlywheel);		//Allow wheels to run

		switch(flySetting){

		case 0:
			displayLCDCenteredString(1, "0");
			flySpeed = 80;
			break;

		case 1:
			displayLCDCenteredString(1, "1");
			flySpeed = 85;
			break;

		case 2:
			displayLCDCenteredString(1, "2");
			flySpeed = 90;
			break;

		case 3:
			displayLCDCenteredString(1, "3");
			flySpeed = 95;
			break;

		case 4:
			displayLCDCenteredString(1, "4");
			flySpeed = 100;
			break;

		case 5:
			displayLCDCenteredString(1, "5");
			flySpeed = 127;
			break;
		}

		motor[LeftTopFly] = flySpeed;
		motor[RightBottomFly] = flySpeed;
		motor[LeftBottomFly] = flySpeed;
		motor[RightTopFly] = flySpeed;
	}

	else
	{
		if (flySpeed > 64)
		{
			flySpeed = (flyspeed / 2);
			motor[LeftTopFly] = flySpeed;
			motor[RightBottomFly] = flySpeed;
			motor[LeftBottomFly] = flySpeed;
			motor[RightTopFly] = flySpeed;
		}
		else
		{
			motor[LeftTopFly] = 0;
			motor[RightBottomFly] = 0;
			motor[LeftBottomFly] = 0;
			motor[RightTopFly] = 0;
		}
	}
}
