#pragma config(Motor,  port1,           rightFrontDrive, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightBackDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftBackDrive, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          leftFrontDrive, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//|--- Stop Drive ---|
void stopDrive()
{
	motor[rightFrontDrive] = 0;
	motor[rightBackDrive] = 0;
	motor[leftFrontDrive] = 0;
	motor[leftBackDrive] = 0;
}

//|--- Autonomous Forward ---|
void autoForward(int power, int target)
{
	motor[rightFrontDrive] = power;
	motor[rightBackDrive] = power;
	motor[leftFrontDrive] = power;
	motor[leftBackDrive] = power;
	wait1Msec(target);
}

//|--- Autonomous Backward ---|
void autoBackward(int power, int target)
{
	motor[rightFrontDrive] = -power;
	motor[rightBackDrive] = -power;
	motor[leftFrontDrive] = -power;
	motor[leftBackDrive] = -power;
	wait1Msec(target);
}

//|--- Autonomous Left Strafe ---|
void autoStrafeLeft(int power, int target)
{
	motor[rightFrontDrive] = power;
	motor[rightBackDrive] = -power;
	motor[leftFrontDrive] = -power;
	motor[leftBackDrive] = power;
	wait1Msec(target);
}

//|--- Autonomous Right Strafe ---|
void autoStrafeRight(int power, int target)
{
	motor[rightFrontDrive] = -power;
	motor[rightBackDrive] = power;
	motor[leftFrontDrive] = power;
	motor[leftBackDrive] = -power;
	wait1Msec(target);
}

//|--- Autonomous Left Turn ---|
void autoTurnLeft(int power, int target)
{
	motor[rightFrontDrive] = power;
	motor[rightBackDrive] = power;
	motor[leftFrontDrive] = -power;
	motor[leftBackDrive] = -power;
	wait1Msec(target);
}

//|--- Autonomous Right Turn ---|
void autoTurnRight(int power, int target)
{
	motor[rightFrontDrive] = -power;
	motor[rightBackDrive] = -power;
	motor[leftFrontDrive] = power;
	motor[leftBackDrive] = power;
	wait1Msec(target);
}

//|--- Drive Control User ---|
void driveControl(int power, int turn, int strafe)
{
	motor[rightFrontDrive] = power - turn - strafe;
	motor[rightBackDrive] = power - turn + strafe;
	motor[leftFrontDrive] = power + turn + strafe;
	motor[leftBackDrive] = power + turn - strafe;
}
